server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ed
    username: admin
    password: handsoff
  jpa:
    hibernate:
      naming:
        physical-strategy: demo.elitedata.dbaccess.config.SnakeCaseNamingStrategy
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: OFF